# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master 

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1
  displayName: 'Install NuGet'

- task: NuGetCommand@2
  inputs:
    restoreSolution: 'TestingAssignment/TestingAssignment.sln'
  displayName: 'Restore NuGet Packages'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'TestingAssignment/TestingAssignmentProject.csproj'  
    arguments: '--configuration $(buildConfiguration)'
  displayName: 'Build Main Project'

- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'TestingAssignment/TestingAssignmentProject.Test/TestingAssignmentProject.Test.csproj' 
    arguments: '--configuration $(buildConfiguration) --logger "trx;LogFileName=test_results.xml"'
  displayName: 'Run NUnit Tests'

- task: PublishTestResults@2
  condition: succeededOrFailed()
  inputs:
    testResultsFormat: 'VSTest'
    testResultsFiles: '**/test_results.xml'
  displayName: 'Publish Test Results'


